modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[dependencies.spooky_chatbridge]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.206,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.spooky_chatbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="SERVER"

[[mods]]
modId="spooky_chatbridge"
version="1.0.0"
displayName="SpookyDevz ChatBridge"
authors="SpookyDevz"
description='''Server-side Discord ↔ Minecraft chat bridge with /discord and /chatbridge commands.'''
logoFile="logo.png"

[modproperties.spooky_chatbridge]
    configBackground="minecraft:textures/block/stone.png"