modLoader="neoforge"
loaderVersion="[4,)"
license="${mod_license}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1.206,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="SERVER"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="logo.png"

[modproperties.${mod_id}]
    configBackground="minecraft:textures/block/stone.png"